version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    # volumes:
    #   - ./html:/usr/share/nginx/html
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    # networks:
    #   - nginx_network
    # restart: always

# networks:
#   nginx_network:
#     driver: bridge